<?php

/**
 * @file
 * Primary module hooks for Panolens module.
 */

/**
 * Implements hook_theme().
 */
function panolens_theme() {
  return [
    'panolens_embed_iframe' => [
      'variables' => [
        'placeholder_token' => '',
      ],
    ],
  ];
}

/**
 * Prepares variables for panolens-embed-iframe template.
 *
 * Default template: panolens-embed-iframe.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_panolens_embed_iframe(array &$variables) {
  $variables['foo'] = 'Foo variable description.';
}
